Transaction entity for tracking stake/unstake activity
gysr-io/subgraph pull request #3
Opened 2021-04-24 21:13 UTC by IainM22

Transaction entity for stakes and unstakes. Used to view activity on a particular Geyser.

Note: I removed the code to increment the Geyser `operations` count when a funding is added. We need to know the number of stakes/unstakes to be able to handle pagination. We could create a count separate from operations for this, but I figured it wasn't really useful to count fundings in this any way. Let me know if you disagree.

2021-04-26 13:04 UTC, devinaconley requested changes
This is looking good to me :+1: 

No issues with removing the operation increment from the funding handler. Just throwing it out there, one alternative is that we could add `Funding` as another type of transaction enum.

Also left some minor performance comments inline.

2021-04-26 13:04 UTC, devinaconley commented on src/mappings/geyser.ts
> +  let transaction = Transaction.load(event.transaction.hash.toHexString());
I think best practice here is actually just to create a new entity object with that hash, set the earnings value, and save it out. The data merging with the original entity will be handled automatically and you can avoid an unnecessary load during indexing.

2021-04-26 13:04 UTC, devinaconley commented on src/mappings/geyser.ts
> +  let transaction = Transaction.load(event.transaction.hash.toHexString());
Same comment as above. This load is probably not needed

2021-04-26 13:04 UTC, devinaconley commented on src/mappings/geyser.ts
> +  let transaction = Transaction.load(event.transaction.hash.toHexString());
This assumption that the entity already exists is probably totally fine since the order of events emitted should always be the same (stake/unstake -> rewards -> gysr spent). But this is something to keep an eye on as we adapt to v2.

2021-04-26 23:09 UTC, IainM22 commented on src/mappings/geyser.ts
> +  let transaction = Transaction.load(event.transaction.hash.toHexString());
Good call, thats good to know. I'll make the change!

2021-04-26 23:14 UTC, IainM22 commented
> This is looking good to me 👍
> 
> No issues with removing the operation increment from the funding handler. Just throwing it out there, one alternative is that we could add `Funding` as another type of transaction enum.
> 
> Also left some minor performance comments inline.

Thats a good point, I hadn't thought about including funding transactions here also. We're going to list fundings in other places in the web app, so I think it'll be cleaner to not also mix them in with the transaction history.

2021-04-26 23:23 UTC, IainM22 commented on src/mappings/geyser.ts
> +  let transaction = Transaction.load(event.transaction.hash.toHexString());
Good point. I think with your tip on creating a new entity here and relying on data merging will actually protect us from these events happening in a different order as well.

2021-04-27 01:16 UTC, devinaconley approved these changes
Looks good to me :+1:

2021-04-28 00:12 UTC, merged