Use new Pool terminology
gysr-io/subgraph pull request #8
Opened 2021-05-25 02:32 UTC by IainM22

The thinking here is that for the v2 contracts we can create a new mapping file called `pool.ts` (or something else).  Any events that will have new event signatures like stake/unstake can have separate mappings, one in geyserv1 and one in the new `pool.ts`. Any mappings that can be shared between the two like handleGysrSpent can move from `geyserV1.ts` to a third ‘common’ mappings file.

2021-05-28 01:11 UTC, devinaconley requested changes
This is looking good :ok_hand:

Just some minor comments on style

2021-05-28 01:11 UTC, devinaconley commented on schema.graphql
>    rewardsUSD: BigDecimal!
can we also rename `apy` to `apr` while we're breaking stuff?

2021-05-28 01:11 UTC, devinaconley commented on src/pricing/pool.ts
>    // apy
apr

2021-05-28 01:11 UTC, devinaconley commented on subgraph.template.yaml
> +    name: GeyserV1Factory
Can we make this `GeyserFactoryV1`?

2021-05-28 01:11 UTC, devinaconley commented on src/mappings/platform.ts
> +import { GeyserV1 as GeyserV1Contract } from '../../generated/templates/GeyserV1/GeyserV1'
Can we import this as `GeyserContractV1`?

2021-05-28 01:11 UTC, devinaconley commented on src/mappings/geyserv1.ts
> +  GeyserV1 as GeyserV1Contract,
Can we import this as `GeyserContractV1`?

2021-05-28 01:11 UTC, devinaconley commented on src/mappings/factory.ts
> +import { GeyserV1 as GeyserV1Template } from '../../generated/templates'
Can we import this as `GeyserTemplateV1`?

2021-05-28 01:11 UTC, devinaconley commented on src/mappings/factory.ts
>  // GYSR factory event handling and mapping
should we rename this to `factoryv1.ts`?

2021-05-28 01:11 UTC, devinaconley commented on src/pricing/pool.ts
>  // pricing for geyser information on apy, tvl, and more
*pool

2021-05-28 13:32 UTC, IainM22 commented on src/mappings/factory.ts
>  // GYSR factory event handling and mapping
Yeah I think thats a good idea

2021-05-28 13:33 UTC, IainM22 commented on schema.graphql
>    rewardsUSD: BigDecimal!
Probably an appropriate time to do that

2021-05-30 17:28 UTC, devinaconley approved these changes
looks great, thanks! :+1:

2021-05-30 17:35 UTC, merged